//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 08:56:33 PM MSK 
//


package by.epam.shop.price;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.epam.shop.price package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.epam.shop.price
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPriceByRangeRequest }
     * 
     */
    public GetPriceByRangeRequest createGetPriceByRangeRequest() {
        return new GetPriceByRangeRequest();
    }

    /**
     * Create an instance of {@link GetPriceByRangeResponse }
     * 
     */
    public GetPriceByRangeResponse createGetPriceByRangeResponse() {
        return new GetPriceByRangeResponse();
    }

    /**
     * Create an instance of {@link PriceDetails }
     * 
     */
    public PriceDetails createPriceDetails() {
        return new PriceDetails();
    }

    /**
     * Create an instance of {@link GetPricesByProductRequest }
     * 
     */
    public GetPricesByProductRequest createGetPricesByProductRequest() {
        return new GetPricesByProductRequest();
    }

    /**
     * Create an instance of {@link ProductDetails }
     * 
     */
    public ProductDetails createProductDetails() {
        return new ProductDetails();
    }

    /**
     * Create an instance of {@link GetPricesByProductResponse }
     * 
     */
    public GetPricesByProductResponse createGetPricesByProductResponse() {
        return new GetPricesByProductResponse();
    }

    /**
     * Create an instance of {@link GetPricesByCurrencyRequest }
     * 
     */
    public GetPricesByCurrencyRequest createGetPricesByCurrencyRequest() {
        return new GetPricesByCurrencyRequest();
    }

    /**
     * Create an instance of {@link GetPricesByCurrencyResponse }
     * 
     */
    public GetPricesByCurrencyResponse createGetPricesByCurrencyResponse() {
        return new GetPricesByCurrencyResponse();
    }

    /**
     * Create an instance of {@link DeletePriceRequest }
     * 
     */
    public DeletePriceRequest createDeletePriceRequest() {
        return new DeletePriceRequest();
    }

    /**
     * Create an instance of {@link DeletePriceResponse }
     * 
     */
    public DeletePriceResponse createDeletePriceResponse() {
        return new DeletePriceResponse();
    }

    /**
     * Create an instance of {@link AddPriceRequest }
     * 
     */
    public AddPriceRequest createAddPriceRequest() {
        return new AddPriceRequest();
    }

    /**
     * Create an instance of {@link AddPriceResponse }
     * 
     */
    public AddPriceResponse createAddPriceResponse() {
        return new AddPriceResponse();
    }

    /**
     * Create an instance of {@link UpdatePriceRequest }
     * 
     */
    public UpdatePriceRequest createUpdatePriceRequest() {
        return new UpdatePriceRequest();
    }

    /**
     * Create an instance of {@link UpdatePriceResponse }
     * 
     */
    public UpdatePriceResponse createUpdatePriceResponse() {
        return new UpdatePriceResponse();
    }

}
