//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 08:56:33 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8081", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.epam.shop.price;
